language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update
  - phpenv config-add travis.php.ini
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - phpcs ./src --standard=psr2 -p --encoding=utf-8 --extensions=php

after_script:
 - php vendor/bin/coveralls -v
