parameters:
    mailsystem_tinymce_type.class: Mailsystem\Bundle\UiBundle\Form\Type\TinymceType

services:
    base.form.type.tinymce:
        class: %mailsystem_tinymce_type.class%
        arguments:
            - @oro_config.user
            - @oro_form.provider.html_tag_provider
            - %kernel.cache_dir%
        calls:
            - [setAssetHelper, [@assets.packages]]
        tags:
            - { name: form.type, alias: tinymce }
