datagrid:
  dashboard-mailsystem-recent-recipients-grid:
    options:
      entityHint: recipients
    source:
      type: orm
      acl_resource: mailsystem_recipient_view
      query:
        select:
          - c.id
          - c.email
          - c.skype
          - c.position
          - c.company
          - c.createdAt
        from:
          - { table: MailsystemRecipientBundle:Recipient, alias: c }
    columns:
      email:
        label: "Email"
      skype:
        label: "Skype"
      position:
        label: "Position"
      company:
        label: "Company"
      createdAt:
        frontend_type: datetime
        label: "Created At"
    sorters:
      columns:
        email:
          data_name: c.email
        skype:
          data_name: c.skype
        position:
          data_name: c.position
        company:
          data_name: c.company
        createdAt:
          data_name: c.createdAt
      default: { createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
    options:
      entityHint: recipient
      toolbarOptions:
        hide: true
        pageSize:
          items: [5]
          default_per_page: 5

  mailsystem-recipient-grid:
    options:
        entityHint: recipients
        export: true
    source:
      type: orm
      acl_resource: mailsystem_recipient_view
      query:
        select:
          - c.id
          - c.firstName
          - c.lastName
          - c.email
          - c.phone
          - c.skype
          - c.position
          - c.company
          - c.description
          - c.createdAt
        from:
          - { table: MailsystemRecipientBundle:Recipient, alias: c }
    columns:
      firstName:
        label: "First Name"
      lastName:
        label: "Last Name"
      email:
        label: "Email"
      phone:
        label: "Phone"
      skype:
        label: "Skype"
      position:
        label: "Position"
      company:
        label: "Company"
      createdAt:
        frontend_type: datetime
        label: "Created At"
    sorters:
      columns:
        firstName:
          data_name: c.firstName
        lastName:
          data_name: c.lastName
        email:
          data_name: c.email
        phone:
          data_name: c.phone
        skype:
          data_name: c.skype
        position:
          data_name: c.position
        company:
          data_name: c.company
        createdAt:
          data_name: c.createdAt
      default: { createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
    filters:
      columns:
        firstName:
          type: string
          data_name: c.firstName
        lastName:
          type: string
          data_name: c.lastName
        email:
          type: string
          data_name: c.email
        phone:
          type: string
          data_name: c.phone
        skype:
          type: string
          data_name: c.skype
        position:
          type: string
          data_name: c.position
        company:
          type: string
          data_name: c.company
        createdAt:
          type: datetime
          data_name: c.createdAt
    properties:
      id: ~
      view_link:
        type: url
        route: mailsystem_recipient_view
        params: [ id ]
      update_link:
        type: url
        route: mailsystem_recipient_update
        params: [ id ]
      delete_link:
        type: url
        route: mailsystem_recipient_delete
        params: [ id ]
    actions:
      view:
        acl_resource: mailsystem_recipient_view
        type:         navigate
        label:        mailsystem.recipient.datagrid.view
        icon:         eye-open
        link:         view_link
        rowAction:    true
      update:
        acl_resource: mailsystem_recipient_update
        type:         navigate
        label:        mailsystem.recipient.datagrid.update
        icon:         edit
        link:         update_link
      delete:
        acl_resource: mailsystem_recipient_delete
        type:         delete
        label:        mailsystem.recipient.datagrid.delete
        icon:         trash
        link:         delete_link
    options:
      entityHint: recipient
      export: true
      entity_pagination: true
      toolbarOptions:
        hide: false
        pageSize:
          items: [10, 25, 50, 100]
          default_per_page: 25
