parameters:
    mailsystem_recipient.importexport.template_fixture.recipient.class: Mailsystem\Bundle\RecipientBundle\ImportExport\TemplateFixture\RecipientFixture
    mailsystem_recipient.importexport.normalizer.recipient.class: Mailsystem\Bundle\RecipientBundle\ImportExport\Serializer\Normalizer\RecipientNormalizer

services:
    # Normalizer
    mailsystem_recipient.importexport.normalizer.recipient:
        class: %mailsystem_recipient.importexport.normalizer.recipient.class%
        parent: oro_importexport.serializer.configurable_entity_normalizer
        tags:
            - { name: oro_importexport.normalizer }


    # Template fixture
    mailsystem_recipient.importexport.template_fixture.recipient:
        class: %mailsystem_recipient.importexport.template_fixture.recipient.class%
        tags:
            - { name: oro_importexport.template_fixture }


    # Converter
    mailsystem_recipient.importexport.data_converter.recipient:
        parent: oro_importexport.data_converter.configurable

    mailsystem_recipient.importexport.template_fixture.data_converter.recipient:
        parent: oro_importexport.data_converter.template_fixture.configurable


    # Export processor
    mailsystem_recipient.importexport.processor.export.recipient:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@mailsystem_recipient.importexport.data_converter.recipient]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %mailsystem_recipient.entity.class%, alias: mailsystem_recipient_recipient }

    mailsystem_recipient.importexport.processor.export_template.recipient:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@mailsystem_recipient.importexport.template_fixture.data_converter.recipient]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %mailsystem_recipient.entity.class%, alias: mailsystem_recipient_recipient }


    # Strategy
    mailsystem_recipient.importexport.strategy.recipient.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace


    # Import processor
    mailsystem_recipient.importexport.processor.import.recipient:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@mailsystem_recipient.importexport.data_converter.recipient]]
             - [setStrategy, [@mailsystem_recipient.importexport.strategy.recipient.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %mailsystem_recipient.entity.class%, alias: mailsystem_recipient_recipient.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %mailsystem_recipient.entity.class%, alias: mailsystem_recipient_recipient.add_or_replace }
