oro_menu_config:
    items:
        mailsystem_recipient_tab:
            label: 'mailsystem.recipient.menu.tab'
            uri: '#'
            extras:
                position: 25

        mailsystem_recipient_manage:
            label: 'mailsystem.recipient.menu.label'
            route: 'mailsystem_recipient_index'
            extras:
                position: 10
                routes: ['mailsystem_recipient_*']

    tree:
        application_menu:
            children:
                mailsystem_recipient_tab:
                    children:
                        mailsystem_recipient_manage: ~

oro_titles:
    mailsystem_recipient_index: ~
    mailsystem_recipient_view: '%%email%%'
    mailsystem_recipient_create: 'Create Recipient'
    mailsystem_recipient_update: '%%email%% - Edit'
