Mailsystem\Bundle\RecipientBundle\Entity\Recipient:
    alias:                          mailsystem_recipient
    title_fields:                   [email]
    route:
        name:                       mailsystem_recipient_view
        parameters:
            id:                     id
    search_template:                MailsystemRecipientBundle:Search:result.html.twig
    fields:
        -
            name:                   firstName
            target_type:            text
            target_fields:          [firstName]
        -
            name:                   lastName
            target_type:            text
            target_fields:          [lastName]
        -
            name:                   email
            target_type:            text
            target_fields:          [email]
