parameters:
    mailsystem_recipient.entity.class: Mailsystem\Bundle\RecipientBundle\Entity\Recipient
    mailsystem_recipient_form.class:   Mailsystem\Bundle\RecipientBundle\Form\Type\RecipientType
    mailsystem_recipient.form.handler.class:  Mailsystem\Bundle\RecipientBundle\Form\Handler\RecipientHandler
    # API
    mailsystem_recipient.recipient.manager.api.class:       Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    mailsystem_recipient.form.type.recipient.api.class: Mailsystem\Bundle\RecipientBundle\Form\Type\RecipientApiType

services:
    mailsystem_recipient_embedded_form:
        class: %mailsystem_recipient_form.class%
        tags:
            - { name: form.type, alias: mailsystem_recipient_request }

    mailsystem_recipient.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "mailsystem_recipient_request"
            - "mailsystem_recipient_request"

    mailsystem_recipient.form.handler:
        class: %mailsystem_recipient.form.handler.class%
        scope: request
        arguments:
            - @mailsystem_recipient.form
            - @request
            - @doctrine.orm.entity_manager

   # Recipient API
    mailsystem_recipient.recipient.manager.api:
        class:                                      %mailsystem_recipient.recipient.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %mailsystem_recipient.entity.class%
            - @doctrine.orm.entity_manager

    mailsystem_recipient.form.type.recipient.api:
        class:                                      %mailsystem_recipient.form.type.recipient.api.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: recipient }

    mailsystem_recipient.form.recipient.api:
        class:                                      Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["recipient", "recipient", null]

    mailsystem_recipient.form.handler.recipient.api:
        class:                                      %mailsystem_recipient.form.handler.class%
        scope: request
        arguments:
            - @mailsystem_recipient.form.recipient.api
            - @request
            - @doctrine.orm.entity_manager