parameters:
    mailsystem_recipient.entity.class: Mailsystem\Bundle\RecipientBundle\Entity\Recipient
    mailsystem_recipient_form.class:   Mailsystem\Bundle\RecipientBundle\Form\Type\RecipientType
    mailsystem_recipient.form.handler.class:  Mailsystem\Bundle\RecipientBundle\Form\Handler\RecipientHandler

services:
    mailsystem_recipient_embedded_form:
        class: %mailsystem_recipient_form.class%
        tags:
            - { name: form.type, alias: mailsystem_recipient_request }

    mailsystem_recipient.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "mailsystem_recipient_request"
            - "mailsystem_recipient_request"

    mailsystem_recipient.form.handler:
        class: %mailsystem_recipient.form.handler.class%
        scope: request
        arguments:
            - @mailsystem_recipient.form
            - @request
            - @doctrine.orm.entity_manager
