mailsystem_maillist_bundle:
  resource: "@MailsystemMaillistBundle/Controller"
  type: annotation

dashboard_mailsystem_maillist:
    resource:     "@MailsystemMaillistBundle/Controller/Dashboard"
    type:         annotation
    prefix:       /dashboard
    options:
        expose: true
