oro_menu_config:
    items:
        mailsystem_tab:
            label: 'mailsystem.menu.tab'
            uri: '#'
            extras:
                routes: ['mailsystem_*']
                position: 45
        mailsystem_letter:
            label: 'mailsystem.letter.menu.label'
            route: 'mailsystem_letter_index'
            extras:
                position: 100
                routes: ['mailsystem_letter_*']

        mailsystem_letter_template:
            label: 'mailsystem.letter_template.menu.label'
            route: 'mailsystem_letter_template_index'
            extras:
                position: 110
                routes: ['mailsystem_letter_template_*']

    tree:
        application_menu:
            children:
                mailsystem_tab:
                    children:
                        mailsystem_letter_template: ~
                        mailsystem_letter: ~

oro_titles:
    mailsystem_letter_index: ~
    mailsystem_letter_view: '%%subject%%'
    mailsystem_letter_create: 'Create Letter'
    mailsystem_letter_update: '%%subject%% - Edit'

    mailsystem_letter_template_index: ~
    mailsystem_letter_template_view: '%%subject%%'
    mailsystem_letter_template_create: 'Create Letter Template'
    mailsystem_letter_template_update: '%%subject%% - Edit'
