datagrid:
  dashboard-mailsystem-recent-maillists-grid:
    options:
      entityHint: maillist
    source:
      type: orm
      acl_resource: mailsystem_maillist_view
      query:
        select:
          - c.id
          - c.name
          - c.createdAt
        from:
          - { table: MailsystemMaillistBundle:Maillist, alias: c }
    columns:
      name:
        label: "Name"
      createdAt:
        frontend_type: datetime
        label: "Created At"
    sorters:
      columns:
        name:
          data_name: c.name
        createdAt:
          data_name: c.createdAt
      default: { createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
    options:
      entityHint: maillist
      toolbarOptions:
        hide: true
        pageSize:
          items: [5]
          default_per_page: 5


  mailsystem-maillist-grid:
    source:
      type: orm
      acl_resource: mailsystem_maillist_view
      query:
        select:
          - c.id
          - c.name
          - c.description
          - c.createdAt
        from:
          - { table: MailsystemMaillistBundle:Maillist, alias: c }
    columns:
      name:
        label: "Name"
      createdAt:
        frontend_type: datetime
        label: "Created At"
    sorters:
      columns:
        name:
          data_name: c.name
        createdAt:
          data_name: c.createdAt
      default: { createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
    filters:
      columns:
        name:
          type: string
          data_name: c.name
        description:
          label: Description
          type: string
          data_name: c.description
        createdAt:
          type: datetime
          data_name: c.createdAt
    properties:
      id: ~
      view_link:
        type: url
        route: mailsystem_maillist_view
        params: [ id ]
      update_link:
        type: url
        route: mailsystem_maillist_update
        params: [ id ]
      delete_link:
        type: url
        route: mailsystem_maillist_delete
        params: [ id ]
    actions:
      view:
        acl_resource: mailsystem_maillist_view
        type:         navigate
        label:        mailsystem.maillist.datagrid.view
        icon:         eye-open
        link:         view_link
        rowAction:    true
      update:
        acl_resource: mailsystem_maillist_update
        type:         navigate
        label:        mailsystem.maillist.datagrid.update
        icon:         edit
        link:         update_link
      delete:
        acl_resource: mailsystem_maillist_delete
        type:         delete
        label:        mailsystem.maillist.datagrid.delete
        icon:         trash
        link:         delete_link
    options:
      entityHint: maillist
      export: true
      entity_pagination: true
      toolbarOptions:
        hide: false
        pageSize:
          items: [10, 25, 50, 100]
          default_per_page: 25
